# This file is used to bind users with roles for role based access control to various resources in kubernetes
# This object falls in the scope of namespaces. By default, it is created for default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <rolebinding_name>
  namespace: <namespace> # Mention namespace if you want to limit your access by namespace
subjects:
- kind: User
  name: <user_name>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: <role_name_to_be_binded_with>
  apiGroup: rbac.authorization.k8s.io