apiVersion: v1
kind: Pod
metadata:
  name: <pod_name>
spec:
  containers:
  - name: <app_name>
    image: <private_image_path> #private-registry.io/apps/internal-app
  imagePullSecrets:
    name: <name_of_secret> # create a secret with `kubectl create secret docker-registry <secret_name>` command with options specifying docker secrets
