# This file is used to bind users with roles for role based access control to various resources in kubernetes
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <rolebinding_name>
subjects:
- kind: User
  name: <user_name>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: <role_name_to_be_binded_with>
  apiGroup: rbac.authorization.k8s.io