apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "10"] # 1 way to specify command
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: # another way to specify commands
    - "sleep"
    - "10"
  - name: nginx
    image: nginx
    command: ["sleep"] # equivalent to ENTRYPOINT in dockerfile
    args: ["5000"] # equivalent to CMD in dockerfiles
