# This file shows different ways to declare sensitive environment variables
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  containers:
  - name: simple-webapp
    image: simple-webapp-color
    envFrom:
      - secretRef:  # will ingest all the secrets defined in secret named app-secret
          name: app-secret
  - name: redis
    image: redis
    env:
      - name: DB_Password
        valueFrom:
          secretKeyRef: # will ingest value for DB_Password key from app-secret for this container
            name: app-secret
            key: DB_Password