# File used by Kubernetes to get configs like clusters, contexts, and users
# YOU DO NOT NEED TO CREATE AN OBJECT FROM THIS FILE AS KUBERNETES TRACKS IT AUTOMATICALLY
# The default location for this file is $HOME/.kube/config

apiVersion: v1
kind: Config
current-context: <user_name>@<cluster_name> # This is an optional field to define the default context
clusters:
- name: <cluster_name>
  cluster:
    certificate-authority: <path_to_ca.crt> # You can instead have `certificate-authority-data field and encoded data instead of path to the file here. Use `cat ca.crt | base64 -w0` command to encode file content`
    server: <server_name>

contexts:
- name: <user_name@cluster_name>
  context:
    cluster: <cluster_name>
    user: <user_name>
    namespace: <namespace_name_if_any> #optional

users:
- name: <user_name>
  user:
    client-certificate: <path_to_admin.crt>
    client-key: <path_to_admin.key>  