# File used to generate a Certificate Signing Request object
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: <name_of_certificate>
spec:
  request: <base 64 encoded csr - run 'cat xyz.csr | base64 -w0' to encode and paste the output here>
  usages:
    - client auth
  signerName: <name_of_signer>